### ISSUE TITLE
Suppressing output

### ISSUE THREAD

**Issue by dennisfisher** [Ljupch0/yfinance#10]
I love yfinance -- however, there is one minor nuisance.
When it runs, this type of output appears:
  Downloading Prices SQ [======================>---------------]  62% ETA:  5s
  Downloading Prices TTD [=======================>-------------]  65% ETA:  4s
  Downloading Prices TTEK [========================>-----------]  69% ETA:  4s
  Downloading Prices UNH [==========================>----------]  73% ETA:  3s
Is it possible to suppress that output?

**Comment by Ljupch0** [comment]
Hi Dennis, thanks for the kind words.

Not out of the box, but you can directly load the package functions and remove `pb <- progress_bar(datatype = "Balance Sheets", ticker)` and `pb$tick` from the definitions, and this will remove the progress bars.

**Comment by dennisfisher** [comment]
Ljupchi

Thanks for getting back to me.  I tried the following:

require("yfinance")
ticker  <- c("AAPL")
function (ticker) 
{
    #pb <- progress_bar(datatype = "Prices", ticker = ticker)
    get_price_proto <- function(ticker, ...) {
        #pb$tick(tokens = list(what = ticker))
        jsonlite::flatten(jsonlite::fromJSON(glue::glue("https://query2.finance.yahoo.com/v10/finance/quoteSummary/{ticker}?modules=price"))[[1]][[1]][[1]]) %>% 
            select(ends_with(".raw")) %>% `names<-`(sub(".raw", 
            "", names(.))) %>% mutate(ticker = ticker, date = Sys.Date()) %>% 
            select(ticker, date, everything())
    }
    safe_download(vector = ticker, proto_function = get_price_proto)
}

I got an error message:
	Error in safe_download(vector = ticker, proto_function = get_price_proto) : 
  could not find function "safe_download"

I presume that this is because safe_download is not exported.  I then commented out that line of code -- this returns nothing.  
And TEMP is:
> TEMP
function(ticker, ...) {
        #pb$tick(tokens = list(what = ticker))
        jsonlite::flatten(jsonlite::fromJSON(glue::glue("https://query2.finance.yahoo.com/v10/finance/quoteSummary/{ticker}?modules=price"))[[1]][[1]][[1]]) %>% 
            select(ends_with(".raw")) %>% `names<-`(sub(".raw", 
            "", names(.))) %>% mutate(ticker = ticker, date = Smake thys.Date()) %>% 
            select(ticker, date, everything())
    }
<environment: 0x7fa9550c7700>

I suspect that I am missing something quite simple -- can you advise how to make this work?

Dennis


Dennis Fisher MD
P < (The "P Less Than" Company)
Phone / Fax: 1-866-PLessThan (1-866-753-7784)
www.PLessThan.com

**Comment by Ljupch0** [comment]
Hi Dennis,

yes you are close. You need to load the utility functions used by all other functions in https://github.com/Ljupch0/yfinance/blob/master/R/utils.R

**Comment by dennisfisher** [comment]
Ljupcho

yfinanc stopped working today —repeated error messages of:

1: In open.connection(con, "rb") :
  cannot open URL 'https://query2.finance.yahoo.com/v10/finance/quoteSummary/AAPL?modules=price': HTTP status was '401 Unauthorized'

Are you aware of this?

Dennis

Dennis Fisher MD
P < (The "P Less Than" Company)
Phone / Fax: 1-866-PLessThan (1-866-753-7784)
www.PLessThan.com <http://www.plessthan.com/>

**Comment by Ljupch0** [comment]
Yes the yahoo finance api is down, maybe this endpoint has been shut down. Nothing I can do.

**Comment by dennisfisher** [comment]
unfortunate!

Dennis Fisher MD
P < (The "P Less Than" Company)
Phone / Fax: 1-866-PLessThan (1-866-753-7784)
www.PLessThan.com <http://www.plessthan.com/>
