### ISSUE TITLE
Errors from get_price()

### ISSUE THREAD

**Issue by tian-y** [Ljupch0/yfinance#11]
I could not get the quote of a ticker 
`
yfinance::get_price("AAPL")
`
and I got this return:

Warning messages:
1: replacing previous import ‘purrr::flatten’ by ‘jsonlite::flatten’ when loading ‘yfinance’ 
2: In safe_download(vector = ticker, proto_function = get_price_proto) :
  There were ERRORS while downloading data for these items: AAPL.
Please check if you have the correct ticker. The vector of errored items and error messages can be accessed as attributes of the returned dataframe - attributes(df).

R version 4.1.2 (2021-11-01) -- "Bird Hippie"

Has anyone else encountered similar issues?

**Comment by Ljupch0** [comment]
API is down, so there's nothing I can do. What kind of data are you looking for? In get_prices you had closing price I believe, you can also get historical and current price data from the quantmod package

https://query2.finance.yahoo.com/v10/finance/quoteSummary/AAPL?modules=price

**Comment by tian-y** [comment]
> API is down, so there's nothing I can do. What kind of data are you looking for? In get_prices you had closing price I believe, you can also get historical and current price data from the quantmod package
> 
> https://query2.finance.yahoo.com/v10/finance/quoteSummary/AAPL?modules=price

Thanks. `quantmod::getQuote("AAPLE")` is also not working. 

Based on [this discussion](https://github.com/joshuaulrich/quantmod/issues/390#issuecomment-1634369026), I think the issue is related to the GDPR regulation in EU countries. It also doesn't seem to be fixable at the moment.
