### ISSUE TITLE
Error in open.connection(con, "rb") : HTTP error 404.

### ISSUE THREAD

**Issue by ivoggv** [Ljupch0/yfinance#7]
Hi, I'm getting this code while trying to run the package. Any ideas of the source of the issue? Thank you.

**Comment by Ljupch0** [comment]
Hi, please be more specific when submitting issues. Which code did you run? In this case I know you were trying to run `yfinance::get_company_names()`. That API endpoint has been shut down, so I will rewrite the function to use a different one. For the time being you can use `yfinance::search_stock(search_term = "AAPL", keep_results = "top")` where you can get the shortname and longname variables.
