### ISSUE TITLE
error in yfinance::get_summaries()

### ISSUE THREAD

**Issue by mabuimo** [Ljupch0/yfinance#8]
```
ticker <- "AA"

company_name <- yfinance::get_company_names(ticker)
summary <- yfinance::get_summaries(ticker)
```
yields:
`Error in open.connection(con, "rb") : HTTP error 404.`

**Comment by Ljupch0** [comment]
hi, `get_company_names` is deprecated, I'm removing it from the package.

You can get the company names here `yfinance::search_stock("AAPL", keep_results = "top")`
